name: Build Docker Image
on:
  push:
    branches: 
      - 'main'
  workflow_call:
    outputs: 
      docker_image: 
        value: ${{ steps.image_name.outputs.DOCKER_IMAGE }}
  
jobs:
  build_image:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE: metadata-cleaner:${{ github.run_id }}
    steps:
    - name: Checkout to main
      uses: actions/checkout@v4
    - name: Set Docker image name variable
      id: image_name
      run: |
        IMAGE=metadata-cleaner:${{ github.run_id }}
        echo "docker_image=$IMAGE" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build --tag $IMAGE .
